# Just the Docs config
title: IU Computational Pathology
description: Advancing diagnostics through computational innovation
theme: just-the-docs
url: "https://azhargro.github.io"
baseurl: ""

# Sidebar navigation options
just_the_docs:
  search_enabled: true
  heading_anchors: true

# Optional nav control
nav_sort: case_insensitive

# Author and metadata
social:
  name: IU Computational Pathology
  email: pathology@iu.edu

# Optional image used for SEO
social_preview_image: /assets/images/iu-comp-path-banner.jpg

# Kramdown settings (Markdown engine)
kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: highlight
    block:
      line_numbers: true
