# Chirpy config
title: IU Computational Pathology
tagline: Advancing diagnostics through computational innovation
description: >-
  The Division of Computational Pathology at Indiana University is dedicated to advancing diagnostics through computational innovation.
url: "https://azhargro.github.io"
baseurl: ""
avatar: /assets/images/indiana_university_logo.jpg
theme: jekyll-theme-chirpy
lang: en
timezone: America/Indiana/Indianapolis

paginate: 10
paginate_path: "/page:num"

collections:
  tabs:
    output: true
    sort_by: order

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      comments: true
      toc: true
      permalink: /posts/:title/
  - scope:
      path: ""
      type: tabs
    values:
      layout: page
      permalink: /:title/

toc: true

social:
  name: IU Computational Pathology
  email: pathology@iu.edu
  links:
    - https://twitter.com/username
    - https://github.com/azhargro

pwa:
  enabled: true
  cache:
    enabled: true

# Optional (safe to keep)
kramdown:
  footnote_backlink: "&#8617;&#xfe0e;"
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: highlight
    block:
      line_numbers: true
      start_line: 1

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - README.md
  - _config_docs.yml
